// ui/app/src/components/DashboardList.tsx
// Copyright 2022 The Perses Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import { DashboardResource } from '@perses-dev/core';
import { useNavigate } from 'react-router-dom';
import { Divider, List, ListItem, ListItemButton, ListItemText } from '@mui/material';

export interface DashboardListProperties {
  dashboardList: DashboardResource[];
}

function DashboardList(props: DashboardListProperties) {
  const navigate = useNavigate();
  return (
    <List>
      {props.dashboardList.map((dashboard, i) => {
        return (
          <>
            {i !== 0 && <Divider key={`divider-${i}`} />}
            <ListItem
              disablePadding
              sx={{ backgroundColor: (theme) => theme.palette.primary.main + '10' }}
              key={`list-item-${i}`}
            >
              <ListItemButton
                onClick={() =>
                  navigate(`/projects/${dashboard.metadata.project}/dashboards/${dashboard.metadata.name}`)
                }
              >
                <ListItemText primary={dashboard.metadata.name} />
              </ListItemButton>
            </ListItem>
          </>
        );
      })}
    </List>
  );
}

export default DashboardList;

// internal/api/front/perses/src/app/project/dashboard/dashboard-list/dashboard-list.component.ts
// Copyright 2021 The Perses Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import { Component, OnInit } from '@angular/core';
import { DashboardService } from '../service/dashboard.service';
import { DashboardModel } from '../model/dashboard.model';
import { ToastService } from '../../../shared/service/toast.service';
import { ProjectService } from '../../project.service';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard-list.component.html',
  styleUrls: ['./dashboard-list.component.scss']
})
export class DashboardListComponent implements OnInit {

  isLoading = false;
  dashboards: DashboardModel[] = [];
  currentProject = '';

  constructor(private readonly service: DashboardService,
              private readonly toastService: ToastService,
              private readonly projectService: ProjectService) {
  }

  ngOnInit(): void {
    this.projectService.getCurrent().subscribe(
      res => {
        this.currentProject = res;
        this.getDashboards();
      }
    );
  }

  private getDashboards(): void {
    this.isLoading = true;
    this.service.list(this.currentProject).subscribe(
      responses => {
        this.dashboards = responses;
        this.isLoading = false;
      },
      error => {
        this.toastService.error(error);
        this.isLoading = false;
      },
    );
  }
}

<app-page>
  <app-page-header>
    <h1>Dashboards</h1>
    <button mat-raised-button color="primary">
      <mat-icon inline>add</mat-icon>
      New
    </button>
  </app-page-header>

  <app-page-content>
    <mat-spinner *ngIf="isLoading"></mat-spinner>
    <app-page-sub-content *ngIf="!isLoading">
      <ul>
        <li *ngFor="let dashboard of dashboards">
          <a routerLink="{{dashboard.metadata.name}}" (click)="onGoToDashboard(dashboard)">{{dashboard.metadata.name}}</a>
        </li>
      </ul>
    </app-page-sub-content>
  </app-page-content>
</app-page>
